#!/usr/bin/env node
/**
 * build-content.mjs — turns everything editable into the files the site reads.
 *
 * Netlify runs this on every deploy (see netlify.toml), so saving something in
 * the owner's panel at /manage commits a file here, which triggers a deploy, which
 * runs this, which updates the site. There is no database anywhere.
 *
 * Inputs
 *   content/settings.json        links, listings, tracking ID   -> config.js
 *   content/reviews/*.json       one file per review            -> reviews-data.js
 *   content/reviews-collected.json reviews gathered off-site     -> reviews-data.js
 *   content/pairs/*.json         before/after pairs             -> photo-manifest.js
 *   content/photos/*.json        single photos                  -> photo-manifest.js
 *   assets/img/gallery/<service>/ files dropped straight in     -> photo-manifest.js
 *
 * Run it by hand any time to preview locally:  node tools/build-content.mjs
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = join(ROOT, 'content');
const GALLERY = join(ROOT, 'assets', 'img', 'gallery');

const SERVICES = {
  'tree-surgery': 'Tree surgery',
  'hedge-cutting': 'Hedge cutting',
  'garden-work': 'Garden work',
  'power-washing': 'Power washing',
};
const IMAGE_EXT = new Set(['.webp', '.jpg', '.jpeg', '.png', '.avif']);

const warnings = [];
const log = [];

/* ------------------------------------------------------------------ utils */
function readJson(path, fallback) {
  if (!existsSync(path)) return fallback;
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    warnings.push(`${path.replace(ROOT + '/', '')} is not valid JSON (${error.message}) — skipped.`);
    return fallback;
  }
}

function readCollection(dir) {
  const full = join(CONTENT, dir);
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => ({ file: f, data: readJson(join(full, f), null) }))
    .filter((e) => e.data);
}

const jsWarning = (name) =>
  `/* AUTO-GENERATED by tools/build-content.mjs — do not edit by hand.\n` +
  `   Edit it at /manage, or in content/, and it rebuilds on deploy.\n` +
  `   Source: ${name} */\n`;

/* ------------------------------------------------------------- 1. config */
const settings = readJson(join(CONTENT, 'settings.json'), {});

const facebook = (settings.facebook || [])
  .filter((f) => f && f.enabled !== false && f.url)
  .map((f) => ({ label: f.label || '', url: f.url }));

const directories = (settings.directories || [])
  .filter((d) => d && d.enabled === true && d.url)
  .map((d) => ({ name: d.name, url: d.url }));

const configOut =
  jsWarning('content/settings.json') +
  'window.PG_CONFIG = ' +
  JSON.stringify(
    {
      facebook,
      google: settings.google || { reviewsUrl: '', writeUrl: '', mapsUrl: '', placeId: '' },
      ga4Id: settings.ga4Id || '',
      directories,
      // filled in by tools/setup.mjs, which owns the phone numbers and domain
      phone1: settings.phone1 || { number: '', label: '' },
      phone2: settings.phone2 || { number: '', label: '' },
      email: settings.email || '',
      domain: settings.domain || '',
    },
    null,
    2
  ) +
  ';\n';

writeFileSync(join(ROOT, 'assets', 'js', 'config.js'), configOut);
log.push(`config.js: ${facebook.length} Facebook page(s), ${directories.length} directory listing(s) switched on`);

/* ------------------------------------------------------------ 2. reviews */
const submitted = readCollection('reviews');

const approved = [];
let waiting = 0;
let withheld = 0;

for (const { file, data } of submitted) {
  if (data.consent === false) { withheld++; continue; }
  if (data.approved !== true) { waiting++; continue; }
  if (!data.text || !data.name) {
    warnings.push(`content/reviews/${file} is approved but has no name or text — skipped.`);
    continue;
  }
  approved.push({
    name: data.name,
    area: data.area || '',
    service: data.service || '',
    rating: Number(data.rating) || 5,
    date: (data.date || '').slice(0, 10),
    text: data.text,
    consent: true,
  });
}

/* Reviews the business collected away from the website — in person, by text
   and on Facebook — rather than through the form on this site. They live in
   one file instead of one file each simply because they arrived in one go.

   From here on they are not treated differently in any way. The owner's
   reviews are one set: a review left through the form on this site joins the
   same list, sorted into the same order by date, and printed identically. It
   is where all his reviews go. Nothing on the page distinguishes them,
   because nothing about them differs that a customer would care about. */
const collected = readJson(join(CONTENT, 'reviews-collected.json'), { enabled: false, reviews: [] });
const collectedOn = collected.enabled === true && Array.isArray(collected.reviews) && collected.reviews.length > 0;
const collectedReviews = collectedOn ? collected.reviews : [];

/* One list, newest first. Sorting after the two sources are joined is what
   makes a review left on the site this morning appear above one collected
   last year, rather than the two sets sitting in separate blocks.

   A review with no date sorts to the TOP, not the bottom. This matters more
   than it looks: a plain date comparison puts an empty string last, so a
   review typed in without a date landed at the very end of a list hundreds
   long — published, correct, and somewhere nobody would ever scroll to. It
   read exactly like the panel had failed to save it. A review with no date is
   almost always one just added, so the top is both the safer guess and the
   place where a mistake is visible instead of hidden. */
const sortKey = (r) => (r.date ? String(r.date) : '9999-99-99');
const allReviews = approved.concat(collectedReviews);
allReviews.sort((a, b) => sortKey(b).localeCompare(sortKey(a)));

const undated = allReviews.filter((r) => !r.date).length;
if (undated) {
  warnings.push(
    `${undated} published review(s) have no date. They are shown at the top of the ` +
    `list and print without one. Add a date in the admin panel to place them properly.`
  );
}

const reviewsOut =
  jsWarning('content/reviews/*.json and content/reviews-collected.json') +
  `\n/* ${allReviews.length} published review(s): ${approved.length} left through the form on` +
  ` this website and ${collectedReviews.length} collected away from it, in one list.` +
  `\n   ${waiting} waiting for approval and ${withheld} withheld for consent are not included. */\n\n` +
  'window.PG_REVIEWS = ' + JSON.stringify(allReviews, null, 1) + ';\n';

writeFileSync(join(ROOT, 'assets', 'js', 'reviews-data.js'), reviewsOut);
log.push(`reviews-data.js: ${allReviews.length} published (${approved.length} from the form, ${collectedReviews.length} collected), ${waiting} waiting, ${withheld} withheld`);

/* ------------------------------------------------------------- 3. photos */
const services = {};
for (const [slug, label] of Object.entries(SERVICES)) {
  services[slug] = { slug, label, pairs: [], singles: [] };
}

// 3a. entries created in the admin panel
for (const { file, data } of readCollection('pairs')) {
  const slug = data.service;
  if (!services[slug]) { warnings.push(`content/pairs/${file}: unknown service "${slug}".`); continue; }
  if (data.published === false) continue;
  if (!data.before || !data.after) {
    warnings.push(`content/pairs/${file}: a pair needs both a before and an after photo — not published.`);
    continue;
  }
  const title = data.title || `${services[slug].label} — before and after`;
  services[slug].pairs.push({
    id: basename(file, '.json'),
    before: data.before,
    after: data.after,
    altBefore: data.alt || `${title} — before PG Gardening & Tree Surgeon started work`,
    altAfter: data.alt || `${title} — the same spot after the job was finished`,
    title,
    caption: data.caption || '',
  });
}

for (const { file, data } of readCollection('photos')) {
  const slug = data.service;
  if (!services[slug]) { warnings.push(`content/photos/${file}: unknown service "${slug}".`); continue; }
  if (data.published === false) continue;
  if (!data.image) { warnings.push(`content/photos/${file}: no image.`); continue; }
  services[slug].singles.push({
    src: data.image,
    alt: data.alt || `${services[slug].label} carried out by PG Gardening & Tree Surgeon`,
    caption: data.caption || '',
  });
}

// 3b. files dropped straight into assets/img/gallery/<service>/
const captions = readJson(join(GALLERY, 'captions.json'), {});

function classify(filename) {
  const stem = basename(filename, extname(filename)).toLowerCase();
  const m = stem.match(/^(before|after|photo)[-_ ]?(\d+)?$/);
  return m ? { kind: m[1], index: m[2] || '01' } : null;
}

for (const [slug, label] of Object.entries(SERVICES)) {
  const dir = join(GALLERY, slug);
  if (!existsSync(dir) || !statSync(dir).isDirectory()) continue;

  const files = readdirSync(dir)
    .filter((f) => !f.startsWith('.') && IMAGE_EXT.has(extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, 'en-GB', { numeric: true }));

  const befores = new Map();
  const afters = new Map();

  for (const file of files) {
    const web = `/assets/img/gallery/${slug}/${file}`;
    const meta = captions[`${slug}/${file}`] || {};
    const info = classify(file);

    if (!info || info.kind === 'photo') {
      services[slug].singles.push({
        src: web,
        alt: meta.alt || `${label} carried out by PG Gardening & Tree Surgeon`,
        caption: meta.caption || '',
      });
    } else if (info.kind === 'before') {
      befores.set(info.index, { src: web, meta });
    } else {
      afters.set(info.index, { src: web, meta });
    }
  }

  for (const [index, before] of [...befores.entries()].sort((a, b) =>
    a[0].localeCompare(b[0], 'en-GB', { numeric: true })
  )) {
    const after = afters.get(index);
    if (!after) {
      warnings.push(`${slug}: before-${index} has no matching after-${index}. Pair not published.`);
      continue;
    }
    const title = before.meta.title || after.meta.title || `${label} — before and after`;
    services[slug].pairs.push({
      id: `${slug}-${index}`,
      before: before.src,
      after: after.src,
      altBefore: before.meta.alt || `${title} — before PG Gardening & Tree Surgeon started work`,
      altAfter: after.meta.alt || `${title} — the same spot after the job was finished`,
      title,
      caption: before.meta.caption || after.meta.caption || '',
    });
  }

  for (const index of afters.keys()) {
    if (!befores.has(index)) {
      warnings.push(`${slug}: after-${index} has no matching before-${index}. Pair not published.`);
    }
  }
}

const totals = Object.values(services).reduce(
  (acc, s) => ({ pairs: acc.pairs + s.pairs.length, singles: acc.singles + s.singles.length }),
  { pairs: 0, singles: 0 }
);

writeFileSync(
  join(ROOT, 'assets', 'js', 'photo-manifest.js'),
  jsWarning('content/pairs, content/photos and assets/img/gallery') +
    'window.PG_PHOTOS = ' +
    JSON.stringify({ generated: new Date().toISOString(), totals, services }, null, 2) +
    ';\n'
);
log.push(`photo-manifest.js: ${totals.pairs} before/after pair(s), ${totals.singles} standalone photo(s)`);

/* -------------------------------------------------------------- 4. report */
console.log('Content built:');
for (const line of log) console.log('  ' + line);

if (warnings.length) {
  console.log('\nWarnings:');
  for (const w of warnings) console.log('  - ' + w);
}
